[package]
name = "morph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.3.0"
chumsky = "1.0.0-alpha.4"
logos = "0.13.0"
num-traits = "0.2.16"
paste = "1.0.12"
rust_decimal = {version = "1.30.0", features = ["maths"]}
rust_decimal_macros = "1.30.0"
